language: node_js

node_js:
  - "4"

cache:
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache
    - node_modules

before_install:
  - "npm i -g yarn"
  - "npm --version"

install:
  - "yarn install --no-progress"

script:
  - "yarn test"

after_success:
  - "cat ./coverage/lcov.info | coveralls"