language: node_js

node_js:
  - "4"
  - "6"
  - "7"

cache:
  directories:
    - node_modules

before_install:
  - "npm config set spin false"
  - "npm --version"

install:
  - "npm install"

script:
  - "npm test"

after_success:
  - "cat ./coverage/lcov.info | coveralls"